# Generated by Django 2.2b1 on 2019-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
